# Site settings
title: Rachit gulati
email: rachitgulati26@gmail.com
permalink: /blog/:year/:month/:title/
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.rachitgulati.com" # the base hostname & protocol for your site
twitter_username: squiroid
github_username:  rachitGulati

# Build settings
markdown: kramdown

books:

- name: "The Alchemist"
  thumb: "the_alchemist"
  author: "Paulo Coelho"
  completed_date: "July, 2017"
- name: "The Pragmatic Programmer"
  thumb: "the_pragmatic_programmer"
  author: "Andrew Hunt & David Thomas"
  completed_date: "July, 2017"
- name: "Harry Potter and the Deathly Hallows"
  thumb: "harry_potter_7"
  author: "J.K. Rowling"
  completed_date: "May, 2017"
- name: "Talent Is Overrated"
  thumb: "talent_is_overrated"
  author: "Geoffrey Colvin"
  completed_date: "Feb, 2017"
- name: "Harry Potter and the Half-Blood Prince"
  thumb: "harry_potter_6"
  author: "J.K. Rowling"
  completed_date: "Jan, 2017"
- name: "Harry Potter and the Order of the Phoenix"
  thumb: "harry_potter_5"
  author: "J.K. Rowling"
  completed_date: "Nov, 2016"
- name: "The Amazon Way: 14 Leadership Principles Behind the World's Most Disruptive Company"
  thumb: "amazon_way"
  completed_date: "Oct, 2016"
  author: "John Rossman"
- name: "Super Brand You"
  thumb: "super_brand_you"
  author: "Ajay Jain"
  completed_date: "Oct, 2016"
- name: "Harry Potter and the Goblet of Fire"
  thumb: "harry_potter_4"
  author: "J.K. Rowling"
  completed_date: "Jul, 2016"
- name: "Harry Potter and the Prisoner of Azkaban"
  thumb: "harry_potter_3"
  author: "J.K. Rowling"
- name: "Harry Potter and the Chamber of Secrets"
  thumb: "harry_potter_2"
  author: "J.K. Rowling"
- name: "Harry Potter and the Philosopher's Stone"
  thumb: "harry_potter_1"
  author: "J.K. Rowling"
- name: "Shantaram"
  thumb: "shantaram"
  author: "Gregory David Roberts"
- name: "Zero to One: Notes on Start Ups, or How to Build the Future"
  thumb: "zero_to_one"
  author: "Blake Masters and Peter Thiel"  
- name: "Elon Musk: Tesla, SpaceX, and the Quest for a Fantastic Future"
  thumb: "elon_musk"
  author: "Ashlee Vance"

adventures:
- images: 
  - src: "https://dl.dropboxusercontent.com/s/a4ak5yfp64hj60d/Screenshot%202016-11-25%2011.07.24.png?dl=0"
    title: "Day 1"
  - src: "https://dl.dropboxusercontent.com/s/zskzi9vhcshwo2r/Screenshot%202016-11-25%2011.07.02.png?dl=0"
    title: "Day 2"
  - src: "https://dl.dropboxusercontent.com/s/le70ymj1hyew1xe/Screenshot%202016-11-25%2011.07.41.png?dl=0"
    title: "Day 3"
  - src: "https://dl.dropboxusercontent.com/s/4ucl0h4epk951xx/Screenshot%202016-11-27%2012.05.46.png?dl=0"
    title: "Day 4"
  - src: "https://dl.dropboxusercontent.com/s/rljp8d01fn8vaqg/download.png?dl=0"
    title: "Day 5 (Recovery Run)"
  - src: "https://dl.dropboxusercontent.com/s/jwdtu3vvrho6pt9/chilling_relax.jpg?dl=0"
    title: "Day 6 (Relaxing Zone)"
  - src: "https://dl.dropboxusercontent.com/s/2m0hwbs10ah0knl/yogaforrunners1.jpg?dl=0"
    title: "Day 7 (Yoga Day for Stretching)"    
  - src: "https://dl.dropboxusercontent.com/s/2m0hwbs10ah0knl/yogaforrunners1.jpg?dl=0"
    title: "Day 8 - Day 15 (Sleeping and Enjoying) 🤘"
  title: "PRACTICE FOR THE 9TH GURGAON RUNNING AND LIVING MARATHON AND A HALF! DEC 11TH 2016 (21KM)"
  description: "Finally 21KM in 2:33 minutes 😊 Yippi 🙃"

games:
- name: "Save My Duck"
  link: "http://rachitgulati.github.io/SaveMyDuck/"
  category: "Web"
  icon: "save-my-duck"

apps:
- name: "CodeBook"
  thumb: "codebook"
  link: "https://play.google.com/store/apps/details?id=com.codebook"
  category: "Android"
- name: "Sum It Up"
  thumb: "sumitup"
  link: "http://rachitgulati.github.io/sum-it-up/"
  category: "Chrome"
#- name: "Chat Panel"
#  thumb: "chat-panel"
#  link: "http://chat-squiroid.rhcloud.com/"

quiz:
- category: "theory"
  set: "one"
  link: "/quiz/2016/11/ques1/"
  question: "How many address modes present for microprocessor ?"
  answer: "There are five only."
- category: "theory"
  set: "one"
  link: "/quiz/2016/11/ques2/"
  question: "Arrange complexity in asc order of time: O(n), O(n^2), O(n!), O(logn), O(nlogn), O(2^n), O(1);"
  answer: "O(1) < O(logn) < O(n) < O(nlogn) < O(n^2) < O(2^n) < O(n!)"
- category: "theory"
  set: "one"
  link: "/quiz/2016/11/ques3/"
  question: "Arrange complexity in asc order of time: O(log(n)), O(log(n!)), O(n^2), O(n)"
  answer: "O(log(n)) < O(n) < O(nlog(n)) < O(n^2)"