# Site settings
title: Rachit gulati
email: rachitgulati26@gmail.com
permalink: /blog/:year/:month/:title/
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://rachitgulati.com" # the base hostname & protocol for your site
twitter_username: squiroid
github_username:  rachitGulati

# Build settings
markdown: kramdown

games:
- name: "Save My Duck"
  link: "save-my-duck"
  category: "Web"

apps:
- name: "CodeBook"
  thumb: "codebook"
  link: "https://play.google.com/store/apps/details?id=com.codebook"
  category: "Android"
#- name: "Chat Panel"
#  thumb: "chat-panel"
#  link: "http://chat-squiroid.rhcloud.com/"